
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Debugger.Options
{
	public partial class OptionPanel
	{
		private global::Gtk.Table table1;
		private global::Gtk.Entry gdbBinPath;
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Debugger.Options.OptionPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Debugger.Options.OptionPanel";
			// Container child MonoDevelop.Debugger.Options.OptionPanel.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.gdbBinPath = new global::Gtk.Entry ();
			this.gdbBinPath.CanFocus = true;
			this.gdbBinPath.Name = "gdbBinPath";
			this.gdbBinPath.IsEditable = true;
			this.gdbBinPath.InvisibleChar = '•';
			this.table1.Add (this.gdbBinPath);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.gdbBinPath]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("<b>Gdb Binary</b>");
			this.label1.UseMarkup = true;
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
